version: '3'
services:
  postgresdb:
    image: postgis/postgis
    container_name: postgres
    ports:
      - 5433:5432 
    volumes:
      - pastebin-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin

volumes:
  pastebin-postgres: