# This docker-compose file is only for local development purposes.
version: '3'
services:
  postgres:
    image: postgis/postgis
    container_name: postgres
    ports:
      - 5433:5433
    volumes:
      - pastebin-postgres:/var/lib/postgresql/data

volumes:
  pastebin-postgres:
